name: Python lint

on: pull_request

env:
  PYTHON_VERSION: "3.10"

jobs:
  python-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Poetry Install Dependencies
        run: |
          poetry install
      - name: Lint
        run: |
          make lint
